[package]
name = "rinha-backend-enrell-rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lb"
path = "src/bin/lb.rs"

[[bin]]
name = "api"
path = "src/bin/api.rs"

[[bin]]
name = "preprocess"
path = "src/bin/preprocess.rs"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
strip = true
